[package]
name = "sltest"
version = "0.1.0"
authors = ["Alec Matusis <matusis@matusis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.29"
rand = "0.7"
tempfile = "3.1"
